### ISSUE TITLE
Increase namespace discoverability by allowing for recursive namespace listing

### ISSUE THREAD

**Issue by jhford** [taskcluster/taskcluster-index#2]
Assume we have the following namespaces:

* a
* a.b
* a.b.c

And the following task:

* a.b.c.task1

To get a copy of each of the namespaces, we would have to call listNamepsaces on the root namespace to find namespace a.  We would then have to call listNamespaces on a to find b, then we'd need to call listNamespaces on b to find c, then we'd need to listTasks on c to find task1.

Since all of this information is able to be computed using the API, it must be possible to be computed inside the API.  It would be great if we could do this recursion in the API itself instead of forcing each consumer to implement this logic for themselves.

I'm not entirely sure what the performance considerations are for this

**Comment by jonasfj** [comment]
> I'm not entirely sure what the performance considerations are for this
He he, I'm pretty sure they are significant...

Well, it depends on what exactly you're suggesting... But we having paging for a reason.
Ie. we can't return a hierarchy with everything from the index because the index is intended to be big.

Note: You might be suggesting something else... If so please clarify... Personally, I wish the data structure was a bit different so we could list both namespaces and tasks at the same time. But was a data layout design mistake that we now pay for... Ideally, if someone have time we can change it and migrate all the data... (If someone has time).

IMO; a lot can be done by just improving the UI.
